-- MySQL Script generated by MySQL Workbench
-- 05/24/16 16:08:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ubiko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ubiko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ubiko` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Ubiko` ;

-- -----------------------------------------------------
-- Table `Ubiko`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ubiko`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `Ubiko`.`Paciente` (
  `NHC` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellidos` VARCHAR(15) NOT NULL,
  `Direccion` VARCHAR(30) NULL,
  `Estado` VARCHAR(15) NULL,
  `telefono` INT NULL,
  `anotaciones` VARCHAR(255) NULL,
  PRIMARY KEY (`NHC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ubiko`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ubiko`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Ubiko`.`Usuario` (
  `idUsuario` VARCHAR(15) NOT NULL,
  `Password` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ubiko`.`Localizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ubiko`.`Localizacion` ;

CREATE TABLE IF NOT EXISTS `Ubiko`.`Localizacion` (
  `idLocalizacion` VARCHAR(10) NOT NULL,
  `numeroPlanta` INT NULL,
  `nombreLocalizacion` VARCHAR(10) NULL,
  PRIMARY KEY (`idLocalizacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ubiko`.`Cama`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ubiko`.`Cama` ;

CREATE TABLE IF NOT EXISTS `Ubiko`.`Cama` (
  `Localizacion_idLocalizacion` VARCHAR(10) NOT NULL,
  `numeroCama` INT NOT NULL,
  `Paciente_NHCPaciente` VARCHAR(9) NULL,
  PRIMARY KEY (`Localizacion_idLocalizacion`, `numeroCama`),
  INDEX `fk_Cama_Paciente1_idx` (`Paciente_NHCPaciente` ASC),
  INDEX `fk_Cama_Localizacion1_idx` (`Localizacion_idLocalizacion` ASC),
  CONSTRAINT `fk_Cama_Paciente1`
    FOREIGN KEY (`Paciente_NHCPaciente`)
    REFERENCES `Ubiko`.`Paciente` (`NHC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cama_Localizacion1`
    FOREIGN KEY (`Localizacion_idLocalizacion`)
    REFERENCES `Ubiko`.`Localizacion` (`idLocalizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ubiko`.`ubicacionPaciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ubiko`.`ubicacionPaciente` ;

CREATE TABLE IF NOT EXISTS `Ubiko`.`ubicacionPaciente` (
  `Localizacion_idLocalizacion` VARCHAR(10) NOT NULL,
  `Usuario_idUsuario` VARCHAR(15) NOT NULL,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NULL,
  `Paciente_NHC` VARCHAR(9) NOT NULL,
  `Orden` BIGINT NULL,
  PRIMARY KEY (`Localizacion_idLocalizacion`, `Usuario_idUsuario`, `fecha`, `horaInicio`, `Paciente_NHC`),
  INDEX `fk_Paciente_has_Localizacion_Localizacion1_idx` (`Localizacion_idLocalizacion` ASC),
  INDEX `fk_Paciente_has_Localizacion_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_ubicacionPaciente_Paciente1_idx` (`Paciente_NHC` ASC),
  CONSTRAINT `fk_Paciente_has_Localizacion_Localizacion1`
    FOREIGN KEY (`Localizacion_idLocalizacion`)
    REFERENCES `Ubiko`.`Localizacion` (`idLocalizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Localizacion_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Ubiko`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ubicacionPaciente_Paciente1`
    FOREIGN KEY (`Paciente_NHC`)
    REFERENCES `Ubiko`.`Paciente` (`NHC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
